function initializeUI()
    labelInfo = forms.label(form, "a maj", 0, 0, 350, 220)
    estAccelere = forms.checkbox(form, "Accelerer", 10, 220)
    estAfficheReseau = forms.checkbox(form, "Afficher reseau", 10, 240)
    estAfficheInfo = forms.checkbox(form, "Afficher bandeau", 10, 260)
    forms.button(form, "Pause", traitementPause, 10, 285)
    forms.button(form, "Sauvegarder", activerSauvegarde, 10, 315)
    forms.button(form, "Charger", activerChargement, 100, 315)
    forms.button(form, "Réinitialiser fitness max", resetFitnessMax, 100, 285)
end